{
  task : charades,
  paths: {
    ckpt_dir: ./ckpt/,
    cache_dir : ./data_pkl/,
    logs_dir: ./logs/,
    feature_file: /mnt/lustre/rjliang/00_Dataset/VMR/charades_i3d_v0.hdf5,
    glove_path: /mnt/lustre/rjliang/00_Dataset/glove/glove.840B.300d.txt,
    train_path: data/charades_gt/train.json,
    test_path: data/charades_gt/test.json,
    val_path: ""
  },

  train: {
    epochs: 20,
    batch_size: 32,
    lr: 0.001,
    warmup_proportion: 0.01,
    clip_norm: 1.0
  },
  dataprocess: {
      video_augmentation: {
        unchanged: None
        # erosion:    0.05,
        # dilation:    0.1,
      },
      sample_type: truncation,
      label_threshold: 0.01
  },
  model: {
    name: BAN,
    max_vlen: 48,
    max_tlen: 30,
    vdim: 1024,
    dim: 256,
    lstm_layer: 1,
    query_embed_dim: 300,
    fuse_dim: 512,
    pooling_counts: [11, 6, 6],
    sparse_sample: true,
    contrast_dim: 128,
    
    num_heads: 4,
    word_dim: 300,
    char_dim: 100,
    droprate: 0.1,

    topk: 16,
    neighbor: 4,
    negative: 0,
    prop_num: 80,
    gcn:
    {
      num_blocks: 2,
      k: 80,
      hidden_size: 512
    },
  },


  loss:
  {
    NAME : bce_loss,
    min_iou: 0.5,
    max_iou: 1.0,
    hidden_size: 512,
    bce: 2.0,
    td: 0.2,
    refine: 3.0,
    contrast: 0.2,
    offset: 3.0
  }
}
