{
  task : charades,
  paths: {
    ckpt_dir: ./ckpt/,
    cache_dir : ./data_pkl/,
    logs_dir: ./logs/,
    feature_file: /mnt/lustre/rjliang/00_Dataset/VMR/charades_i3d_v0.hdf5,
    glove_path: /mnt/lustre/rjliang/00_Dataset/glove/glove.840B.300d.txt,
    train_path: data/charades_gt/train.json,
    test_path: data/charades_gt/test.json,
    val_path: ""
  },
  train: {
    epochs: 50,
    batch_size: 128,
    lr: 0.0008,
    warmup_proportion: 0.05,
    clip_norm: 1.0
  },
    dataprocess:{
        video_augmentation: {
                                unchanged: None
                                # erosion:    0.05,
                                # dilation:    0.05,
                              },
        sample_type: truncation,
        label_threshold: 0.01
    },
  model: {
    name: SeqPAN,
    max_vlen: 64,
    max_tlen: 30,
    vdim: 1024,
    dim: 128,
    num_heads: 8,
    word_dim: 300,
    char_dim: 100,
    droprate: 0.2,
    num_props: 8,
    div_lambda: 0.146,
    div_loss_alhpa: 1.0
  },
  loss: {
    margin_1: 0.1,
    margin_2: 0.15,
    lambda: 0.146,
    alpha_1: 1,
    alpha_2: 5
  }

}