{
  task : charades,
  paths: {
    ckpt_dir: ./ckpt/,
    cache_dir : ./data_pkl/,
    logs_dir: ./logs/,
    feature_path: /storage_fast/rjliang/charades/feat/i3d_v0,
    glove_path: /storage_fast/rjliang/glove/glove.6B.300d.txt,
    train_path: data/charades_gt/train.json,
    test_path: data/charades_gt/test.json,
    val_path: ""
  },

  train: {
    epochs: 50,
    batch_size: 64,
    lr: 0.0002,
    warmup_proportion: 0.01,
    clip_norm: 1.0
  },
    dataprocess:{
        video_augmentation: {
                                unchanged: None
                                # erosion:    0.05,
                                # dilation:    0.05,
                              },
        sample_type: samelen,
        label_threshold: 0.01
    },
  model: {
    name: VSLNet,
    max_vlen: 128,
    max_tlen: 30,
    vdim: 1024,
    dim: 128,
    num_heads: 8,
    word_dim: 300,
    char_dim: 100,
    droprate: 0.2,
    predictor: rnn,
  },
  loss:{
    highlight_lambda: 5
  }
}