{
    task : anet,
    paths: {
        ckpt_dir: ./ckpt,
        cache_dir : ./data_pkl/,
        logs_dir: ./logs/,
        feature_file: /storage_fast/rjliang/activitynet/feat/c3d_v0,
        glove_path: /storage_fast/rjliang/glove/glove.6B.300d.txt,
        train_path: ./data/anet_i3d_gt/train.json,
        test_path: ./data/anet_i3d_gt/test.json,
        val_path: "",
    },

    train: {
        epochs: 30,
        batch_size: 64,
        lr: 0.0002,
        warmup_proportion: 0.01,
        clip_norm: 1.0
    },
    dataprocess:{
        video_augmentation: {
                                unchanged: None
                                # erosion:    0.05,
                                # dilation:    0.05,
                              },
        sample_type: truncation,
        label_threshold: 0.01
    },
  model: {
    name: CCA,
    max_vlen: 64,
    max_tlen: 30,
    # vdim: 1024,
    # dim: 128,
    # num_heads: 4,
    word_dim: 300,
    # char_dim: 100,
    # droprate: 0.2
  },

  MODEL: {
      WEIGHT: "",
      ARCHITECTURE: "CCA",
      CCA: {
          NUM_CLIPS: 64, # model.max_vlen
          FEATPOOL:{
              INPUT_SIZE: 500, # model.vdim
              HIDDEN_SIZE: 64,
              KERNEL_SIZE: 2
          },
          FEAT2D:{
              POOLING_COUNTS: [15,8,8]
              }, 
          INTEGRATOR:{
              QUERY_HIDDEN_SIZE: 512,
              LSTM:{
                  NUM_LAYERS: 3,
                  BIDIRECTIONAL: True,
              },
          },
          PREDICTOR:{
              HIDDEN_SIZE: 512,
              KERNEL_SIZE: 9,
              NUM_STACK_LAYERS: 4,
          },
          LOSS:{
              MIN_IOU: 0.5,
              MAX_IOU: 1.0,
          },
      },
  },
  INPUT: {
      NUM_PRE_CLIPS: 64,
      PRE_QUERY_SIZE: 300,
  },
  embed_size: 64,
  num_attribute: 3152,
  input_channel: 300,
  adj_file: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_concept_adj.pkl,
  norm_func_type: sigmoid,
  # inp_name: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_concepts_glove_word2vec.pkl
  # concept_name: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_category_concepts.json
  com_concept: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_com_graph.pkl,
  # com_emb: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_test_concepts.pkl
  num_path: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_dict.pkl,
  attri_input_path: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_concepts_glove_word2vec.pkl,
  commonsense_path: /storage/rjliang/4_FastVMR/CCA/acnet_concept/acnet_test_concepts.pkl,


}

