{
    task : anet,
    paths: {
        ckpt_dir: ./ckpt,
        cache_dir : ./data_pkl/,
        logs_dir: ./logs/,
        feature_path: /storage_fast/rjliang/activitynet/feat/i3d_v1,
        glove_path: /storage_fast/rjliang/glove/glove.6B.300d.txt,
        train_path: ./data/anet_i3d_gt/train.json,
        test_path: ./data/anet_i3d_gt/test.json,
        val_path: "",
    },
    train: {
        epochs: 50,
        batch_size: 16,
        lr: 0.0001,
        warmup_proportion: 0.00,
        clip_norm: 1.0
    },
    dataprocess:{
        video_augmentation: {
                                unchanged: None
                                # erosion:    0.05,
                                # dilation:    0.05,
                              },
        sample_type: truncation,
        label_threshold: 0.01
    },
    model: {
        name: SeqPAN,
        max_vlen: 100,
        max_tlen: 100,
        vdim: 1024,
        dim: 128,
        num_heads: 4,
        word_dim: 300,
        char_dim: 100,
        droprate: 0.2
    },
}